### ISSUE TITLE
Wrong utf8 encoding when using berks

### ISSUE THREAD

**Issue by spuder** [spheromak/docker_chefdk#2]
If you attempt to upload a file from docker using berks, you will get this error. 

``` bash
$ berks install --config=.berkshelf/lab.json
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
Installing chef_handler (1.3.0)
Installing iis (4.1.7)
Installing chocolatey (1.0.0)
Using xxxxx(1.11.0) from source at .
Installing windows (1.39.2)
$ berks upload --config=.berkshelf/lab.json
Skipping chef_handler (1.3.0) (frozen)
Skipping chocolatey (1.0.0) (frozen)
Skipping iis (4.1.7) (frozen)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `convert_input'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/engine.rb:38:in `convert!'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/chef/cookbook/syntax_check.rb:137:in `validate_template'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/chef/cookbook/syntax_check.rb:126:in `block in validate_templates'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/chef/cookbook/syntax_check.rb:125:in `each'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/chef/cookbook/syntax_check.rb:125:in `validate_templates'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/chef/cookbook.rb:200:in `validate'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/resources/cookbook_resource.rb:199:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/uploader.rb:55:in `block (2 levels) in upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/uploader.rb:51:in `each'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/uploader.rb:51:in `block in upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley/client.rb:38:in `open'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.0/lib/ridley.rb:56:in `open'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf.rb:144:in `ridley_connection'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/uploader.rb:50:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/uploader.rb:37:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/berksfile.rb:592:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:208:in `upload'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:52:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/lib/berkshelf/cli.rb:27:in `execute!'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.0/bin/berks:5:in `<top (required)>'
    from /usr/bin/berks:48:in `load'
    from /usr/bin/berks:48:in `<main>'
```

This looks to be a known problem with docker containers and ruby

http://jaredmarkell.com/docker-and-locales/

**Comment by spheromak** [comment]
thnx for the PRs should be fixed
